FROM debian:latest

MAINTAINER Steeve Péré "steevepere@gmail.com"

RUN apt-get update -y

RUN apt-get install -y python-pip python-dev build-essential

RUN apt-get install -y apt-transport-https
RUN apt-get install -y ca-certificates
RUN apt-get install -y curl
RUN apt-get install -y gnupg2
RUN apt-get install -y software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
RUN apt update -y
RUN apt-cache policy docker-ce
RUN apt install -y docker-ce

RUN pip install flask
RUN pip install flask-mysql
RUN pip install flask_wtf
RUN pip install flask-bootstrap
